function imagedisp_setting(hObj,event,obj)
            pararead=figure('Name','options','MenuBar','none','ToolBar','none','Tag','dispopt');
            initPosition = pararead.Position;
            pararead.Position = [initPosition(1), ...
                initPosition(2) - 400 + initPosition(4), 300, 170];
            panelsele=uicontrol(pararead,'Style','text','Units','normalized',...
                'String','Panel selection','FontSize',12,...
                'Position',[0.05,0.7,0.4,0.2]);
            panelsele_in=uicontrol(pararead,'Style','popupmenu','Units','normalized',...
                'Tag','panelsele','FontSize',12,'String',{'Main Panel','Panel 2','Panel 3',...
                'Panel 4'},'Position',[0.55,0.7,0.3,0.2]);
            imgsele=uicontrol(pararead,'Style','text','Units','normalized',...
                'String','image to be displayed','FontSize',12,...
                'Position',[0.05,0.475,0.4,0.2]);
            datanamepool={'raw ROI','raw ROI Deconv','raw ROI WBC',...
                'raw ROI Deconv WBC','raw ROI WBC Deconv'};
            dataname=cell(1,1);
            dataname{1,1}='name';
            for i=1:5
                if ~isempty(obj.guihandles.Data{1,i})
                    idx=length(dataname);
                    dataname{1,idx+1}=datanamepool{1,i};
                end
            end
            dataname(ismember(dataname,'name'))=[];
            imgsele_in=uicontrol(pararead,'Style','popupmenu','Units','normalized',...
                'Tag','imgsele','FontSize',12,'String',dataname,'Position',[0.55,0.475,0.3,0.2],'UserData',datanamepool);
            coorsele=uicontrol(pararead,'Style','text','Units','normalized',...
                'String','coordinate selection','FontSize',12,...
                'Position',[0.05,0.25,0.4,0.2]);
            coorsele_in=uibuttongroup(pararead,'Visible','off','Position',[0.5,0.28,0.4,0.2],'Tag','coorsele');
            labcoordi=uicontrol(coorsele_in,'Style','radiobutton','String','Lab','Position',[10,1,60,30],...
                'HandleVisibility','off','FontSize',12);
            biocoordi=uicontrol(coorsele_in,'Style','radiobutton','String','Bio','Position',[60,1,60,30],...
                'HandleVisibility','off','FontSize',12);
            coorsele_in.Visible='on';
            confirmation=uicontrol(pararead,'Style','pushbutton','String','Display',...
                'Units','normalized','Position',[0.35 0.07 0.3 0.15],'FontSize',12,...
                'Callback',@(hObj,event) imagedisp(hObj,event,obj));
        end