function imagerot_setting(hObj,event,obj)
pararead=figure('Name','options','MenuBar','none','ToolBar','none','Tag','imrot_setting');
initPosition = pararead.Position;
pararead.Position = [initPosition(1), ...
    initPosition(2) - 400 + initPosition(4), 300, 170];
axisele=uicontrol(pararead,'Style','text','Units','normalized',...
    'String','Axis seletion','FontSize',12,...
    'Position',[0.05,0.8,0.4,0.15]);
rotangle=uicontrol(pararead,'Style','text','Units','normalized',...
    'String','rotation angle','FontSize',12,...
    'Position',[0.5,0.8,0.4,0.15]);
axisele_in1=uicontrol(pararead,'Style','popupmenu','Units','normalized',...
    'Tag','axisele_in1','FontSize',10,'String',{'x','y','z',...
    },'Position',[0.2,0.78,0.1,0.01]);
axisele_in2=uicontrol(pararead,'Style','popupmenu','Units','normalized',...
    'Tag','axisele_in2','FontSize',10,'String',{'x','y','z',...
    },'Position',[0.2,0.58,0.1,0.01]);
axisele_in3=uicontrol(pararead,'Style','popupmenu','Units','normalized',...
    'Tag','axisele_in3','FontSize',10,'String',{'x','y','z',...
    },'Position',[0.2,0.38,0.1,0.01]);
rotangle_in1=uicontrol(pararead,'Style','edit','Units','normalized',...
    'Tag','axis_in1','FontSize',12,'Position',[0.65,0.64,0.15,0.15]);
rotangle_in2=uicontrol(pararead,'Style','edit','Units','normalized',...
    'Tag','axis_in2','FontSize',12,'Position',[0.65,0.44,0.15,0.15]);
rotangle_in3=uicontrol(pararead,'Style','edit','Units','normalized',...
    'Tag','axis_in3','FontSize',12,'Position',[0.65,0.24,0.15,0.15]);
confirmation=uicontrol(pararead,'Style','pushButton','Units','normalized',...
    'String','Confirm','FontSize',12,'Position',[0.33,0.05,0.3,0.15]);
confirmation.Callback=(@(hObj,event) Fcn_affineTrans(hObj,event,obj));
end